import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'
import prettier from 'eslint-config-prettier'

const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  console: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  fetch: 'readonly',
  XMLHttpRequest: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  process: 'readonly',
  self: 'readonly',
  caches: 'readonly',
  Notification: 'readonly',
  ServiceWorker: 'readonly',
  ServiceWorkerRegistration: 'readonly',
  PushManager: 'readonly',
  PushSubscription: 'readonly',
  Storage: 'readonly',
  StorageEvent: 'readonly',
  WebSocket: 'readonly',
  Worker: 'readonly',
  SharedWorker: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  EventTarget: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  matchMedia: 'readonly',
  MutationObserver: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  getComputedStyle: 'readonly',
  scrollTo: 'readonly',
  history: 'readonly',
  location: 'readonly',
  screen: 'readonly',
  performance: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FileList: 'readonly',
  FormData: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  TextDecoder: 'readonly',
  TextEncoder: 'readonly',
  MessageChannel: 'readonly',
  crypto: 'readonly',
  indexedDB: 'readonly',
  IDBKeyRange: 'readonly',
  Image: 'readonly',
  Audio: 'readonly',
  AudioContext: 'readonly',
  MediaRecorder: 'readonly',
  HTMLElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  DOMParser: 'readonly',
  ClipboardItem: 'readonly',
}

const nodeGlobals = {
  process: 'readonly',
  console: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  Blob: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  FormData: 'readonly',
  structuredClone: 'readonly',
}

// 合并前各应用遗留的未使用变量/组件很多；先降为 warn，避免 CI 被历史债挡住，同时仍能抓住 undef/语法错误
const legacyNoise = {
  'no-unused-vars': [
    'warn',
    { caughtErrors: 'none', argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
  ],
  'vue/no-unused-components': 'warn',
  'vue/no-unused-vars': 'warn',
  'no-useless-catch': 'warn',
  'no-useless-escape': 'warn',
  'no-empty': ['error', { allowEmptyCatch: true }],
  'vue/no-mutating-props': 'warn',
}

export default [
  {
    name: 'monorepo/ignores',
    ignores: [
      '**/dist/**',
      '**/dist-ssr/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/dev-dist/**',
      '**/generated/**',
      '**/pnpm-lock.yaml',
      '**/package-lock.json',
      '**/*.timestamp-*.mjs',
      '**/auto-imports.d.ts',
      '**/components.d.ts',
      '**/typed-router.d.ts',
      '**/vendor/**',
      '**/public/**',
      'apps/server/generated/**',
    ],
  },

  js.configs.recommended,

  ...pluginVue.configs['flat/recommended'],
  {
    name: 'monorepo/vue-apps',
    files: ['apps/web/**/*.{js,mjs,jsx,vue}', 'apps/dashboard/**/*.{js,mjs,jsx,vue}'],
    rules: {
      'vue/multi-word-component-names': 'off',
      ...legacyNoise,
    },
    languageOptions: {
      globals: browserGlobals,
    },
  },

  {
    name: 'monorepo/server',
    files: ['apps/server/**/*.{js,mjs,cjs}'],
    languageOptions: {
      globals: nodeGlobals,
    },
    rules: {
      'vue/multi-word-component-names': 'off',
      ...legacyNoise,
    },
  },

  {
    name: 'monorepo/shared',
    files: ['packages/shared/**/*.js'],
    languageOptions: {
      globals: nodeGlobals,
    },
  },

  prettier,
]
